BfsDfs:
	g++ -g -o testBfsDfs testBfsDfs.cxx dfs.cxx bfs.cxx Graph.cxx
DijkstraPQ: 
	g++ -g -o testDijkstraPQ testDijkstra.cxx  Graph.cxx singleSourceShortest.cxx BinaryHeap.cxx
DijkstraDG: 
	g++ -g -o testDijkstraDG testDijkstra.cxx  Graph.cxx DijkstraDG.cxx
BellmanFord: 
	g++ -g -o testBellmanFord testDijkstra.cxx  Graph.cxx bellmanFord.cxx
FloydWarshall: 
	g++ -g -o testFloydWarshall testFloydWarshall.c  Graph.cxx allPairsShortest.cxx
Prim: 
	g++ -g -o testPrim testPrim.cxx  Graph.cxx Prim.cxx BinaryHeap.cxx
